### ISSUE TITLE
[Bug]: Devtool does not show components errors anymore

### ISSUE THREAD

**Issue by taorepoara** [lenra-io/dev-tools#143]
### What happened?

I tried starting an new app with Lenra, but got a problem because of this issue: https://github.com/lenra-io/dev-tools/issues/142

The error displayed is empty: 

![Capture d’écran du 2022-09-18 10-42-54](https://user-images.githubusercontent.com/8969556/190894416-368bf66d-311d-48e0-9d54-17696718a5a7.png)

### What browsers are you seeing the problem on?

Firefox

### Version

1.0.0-beta.58

### Relevant log output

```Shell
No logs is displayed in the devtool container. This should be imprived two.
```

**Comment by Nesqwik** [comment]
It should be fixed by https://github.com/lenra-io/application-runner/pull/242

I've encounter this issue while i was doing the view system. I've fixed it on the fly to help me debug the feature.
